language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: eexTOMfoT3GzmNs0/j4kFuVuDC78+VO6A+nYTyvdy0Ku9rUGIopUxl5B+AxOgBQu3Ch0SotdjKpoJMVEK7Xv2tIKtVrB/9gDeZWsDZowAiqydTvNBhU3aNPmMcAi7lhTQe27QK6HGw2AoAL7UgmPM50Gcmc97Sdx1+AIHQjx4Hp3oiI0OvH/QFWfeJ/6sY75uxWPE53gmb1QY4/Vuqv6jjeTrp2OCIhdRtnGn/NdD4GT1W/TZfWH6TvuK9ScD5NaZKULtLw+9pIvX4hsOmcxVrhxxIM4s8je0EsF5QlXHBovNiGSPhyTRMegjGn3vSKCnN1t4ebdkpZ3FC2VQE760BjSgesnOwjVm3bZbGIW1jrEVLM20MXyaE74NxPFJJl7CH1QlD1HYLVM6tUyzArMK+Vju+qjs61ajV/Fx+hKvOz93IN2GQlJAbH1/mpTELG9diOOWO5JWA9mgfzWypJsvLmpxQlhKY0HyFcawYniS++txaJifWaqhnPlOi9B4CTx9+ukLH/bq4Rmu+Man5V/oPtR/NxA5ij3av4+udPtFUQMKx5ZFt1jJQn2SQgPZJzGWL0u31BOkCZIIDM06mPSd15Uu19X2EtdDIFyB5mRbd//l4wk4YR66YLjk3NPCNTWUSD5rL/OBQyRxjD3kmsKk6/rEuPdevBNHSmvkjbRpjI=
  app: projetpizza
  on:
    repo: Tilanchicha/ProjetPizza
