language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: DF+62ArN+Vp1a2mn9UsOmA0YVjFliYX0lxOJVEQL8v84UEhIMvOn5fTxxzLozKGrqeSX+CEacukZsAqKw1G6qn2MVTeWzEyhpygvsLs8xhpA6gQALZwd18F87R7mIoKHoYQj1IIdYPmvBDK0uUGyJAuifWphKAWdasI2ZSspPhjFzZSebyJKO2s6cyUzxJMyqUoBO6datZ6kqeeoFEb5k3+PuGLcVgPmNFXxFwIZJ7zlN1+PcDQSy8LfS4YrREl4uB6BjLJuqdQwhR5grt5vO0V0dnTJGHas0qqg91rC58B40kZp7/1LEF7vuxiicS7JP+5pSZe4Up1xFzr+pyj7wvjlJKJbNMmOo0MLlDpZyRq6NCzsNurcZV+2XhMdeEzubGh7WF2WA3XdMO6n8oPuv/bAQeU8WoZQrKXXr5OHyz/+9lBK9+KyjGF6fbl/I1aC1tOwceyBGuHJf4ErwHdqHFBvhWkn/jfCmGLQFp/Oa5nywzraazGKWdPtdZydQNenHYPTIZ2o0YP8FS20edhJimdqZgXJiTtw38A4WXHOPswzs8QHL5wB8e4IugJGdzJudfunvMeesvxPLe/vYGKJHF939pQcBu/YneC5SSum3Jbork6ZFrlHbhLRGOlYgvqJsX/wQLBFceaaTOkBDb65nmywR9V8g2zTgJbp6zus0eA=
  app: lp4apizza
  on:
    repo: Tilanchicha/ProjetPizza
