language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: ust40BVJVVgfVgCi3ay6iFv4bU5P29zxUkyfMNJRAHuo5kcGEAss7sy+WJCBZc+y7grHXyzGwxYlaXxnK6jEswYzIHmhmbs7cAnpvG4nOEer4f0u6ycvhuGNYeY24BqkHiLB0BMxK+lFDRtnSRHSxRleKmQfbVzB0zziV7wFsCmWzk4p2xw8k3/54FLE2IhiFrwu+832AaBpWuVY6DgSwkH05CkvJmP1sMcjkrSkTNjxnOkAd+mLvBCNMhepPusRXue1Wv+ksWRmBsXdHjSTnuFWBcUfLgw8buh4j54G9GmXOEsdYopTkYIHE0W2CDwJ+65vOcRFmgrERJGnBkjA5CuB039wbwq8a+6H4Nlmax4dKvm0I8ygBGrkrAM/u7p0NGfqYBQQdd0B03N70rp7nSfCPUYKmo88oJJ1doEC+Wg7Ng62HCft9kdJyTVYD0xNAfu/v8LVv2vNDYH0yFiBqLPQxZdllY1s5TF7iDpA1mrzwvG1nAPh3Gx70Mkf2/yyWHBAF1SxUCUMPz+Z/4FbB7yiKqYwBLY+BDUzvd1AzzXX65KlJkN0/apDftdGUv6djFK0IweDK4hGMYIagaUrThZftFF+t+9AUqJ/OtrPPojq79l1iIGS8Qex+P0iTEJ93BZjBQq27BSnxuCtYjjLTgzYbKDdFWuOoXJW20RVNgE=
  app: lp4apizza
  on:
    repo: Tilanchicha/ProjetPizza
