language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: eEDXeBGP7TQIujd2sWYWYlG4YcGNd6QqszTAI2Kj23E/Vcn2X//oZqB8EC2pfa7XBwJFAYVnLvzVX9flFBp9AbUbvI9DtjgbGjvLPmalxoe82uToHIyshPH69a2iHeL3zSZBV+G8z+7NSbF3OzQJmoZ877IHTrVSAEenqTv2dqrT9ezU3d7vhkqgpF/Mfll9PMVW+oiLFQ0SPCHoxvoLDl6AMA+uUcUhsbKhT+kOofDj5B4Mq1FjlJA/1pFZ2j8fnTnGXE/ZWZifFH46naXAEwazr5ghbt5aK2AQhsIcFOx0JVEWufN/gIGIRkkp3P201MXEN+LZJWNBVxUz5kCNPsCQTwrRJZaewZdNptfDX/6BfyNbAVWkcAqDICB7cdYge6VruuCXrLOi5wwYY36pXrEgMZjsLItE5cBD0VHsj9PXWh5LGDPfLgozCkDkYg87Ys/Xp5XEGw1+8Vb4Xmy0gjgTp9dOlNMSLoGQX5rMOLiVEgUdupRgKGogJz6hRCQEhZHFSe9dzsfjWht4bOSHNcZ823sAbhPQkdyK/phFuDxLOD+4oAqjRQfgfX/0NZz7yog5frRJW8lW6gKbAVxcqFr7NHNVrLMNwAOxLFGVBZM4I6KCWTrvJ4Y3mWSNiNy6Vw+8s08B9Qhp300cJNhvQSAfy99OA1hTMnTsX85dw3k=
  app: projetpizza
  on:
    repo: Tilanchicha/ProjetPizza
