language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: U6t4ED434FAbd+AJYy0VTkyUDIaCoE5Ilow4KF2o+pZqgV2ob4J3p7ybXd3MQpkhtLPi6wjAzisWyWv5x6bCbqw4fn1LX/D63xyw3UNGvjj7JFWoz1ZBhcXHY3DC9M5L5txUKFyDolqNlLW12UwcF3XxSIqPei9nF4YRtjQeZY5lgKFhM2lAMjZV0IkBx19PtseqBb0XOXGLPeXoYaYLWFYm2Ewh0gaCYblEbZww5xQqgNtp3FTqYt3IR9wERurTCELNnChfh4s/fpvFsqGKzJABEK989g15BLRlcDCK07wqTxrwJk06beTWyi3U0Q4ct3+/++AKePjgNUIA/6kM7V6gzUumXIQh5vDrwoQJPpRBBEOBxg4pocrlHqJkJuXAnDDt8Ml0OtvvXPWSQgkXOSvFDByuOVtCH/ReS63V0aghNxdDRIqQ659qSj/BTzBPckzk5SQpkfsrej/8/LnLI4/HOuhTeB/UNZczlNSipy8gl8HKFdkuOFMcvF66fazXezaiKqFU/YQ82HanPskfR8qLQahC8pCv4CgB26qF6w234kdYSoDVOV84p9YDKybYI0QiDpIUx+8ouqSjTl2YTElpDtg94VAajULR2I6ZlYwU5GGNi8kq2tu6sTKG52SxCjrphPSGC9Thz8X/tJrnf4vCsznWFSc6YBrtE17KY+Y=
  app: lp4apizza
  on:
    repo: Tilanchicha/ProjetPizza
