language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: sq1svWLKFE/BN4nYEM7JCKf8VXZ2HBpY6Pl9LDh7FDJstBtXp+6lqcXCtnXtfA0bHE8T/MofECK+aTngorraYY2V6Kz57sI+ajmskaIY3JO9AV322/agdP0wLqfzTnvd3vtO7bnF2QkT0Un8gvJWbR/zZfcDxfJuUwIM/l4y19CwlSNcGjNQAAli2pF+e33M6f1+Jek8WeuswdFc6tJuj+P4PNc/HuWyM9LcIQI3/fGgFGdIrgo+Qxj+331yTXR9j9om1YRoRiwnSY2nHtTJxLz5+URqolV9lWbS9hAMnv+iWU4XGs0dGbGF3Wy2iGGu22k4WliwQ3vDFZ/TayGJtwMSga4KO/2knU9yaJFoQCUzJVMAO00hPbFpbqGIOqY2MPidQ2pC8wt0/H3ECd9297pizqtgAW4JzalprgFgUQ8n72YvQ04BaIehv7PmjI9W1QjqGhItzdNRzp7wdsrvqSgr+cYWJ0op+mB4cjrFpcswUjo9f9nmXI9td0J6unuRveWgoAwgvbcpERumDS/aG67ElMQKKffWc7Yk2A2mUZNHEY4XgjD4AtVP+Y6K3cfzHcU2n3d2kyWvwixl/lCH2hmusV3rW+HVpf0jgD5I5bdix7nN1DCOPMWoriwSdCXQpDROQn71wfGU8GdOHS8FLfwumhDmRdvHmipiZxB0J/g=
  app: lp4apizza
  on:
    repo: Tilanchicha/ProjetPizza
