language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: f48sO8+3CzT8mPGshUZc3EGbOiSxBa+MQGN+KV5IFBHOli+xiKKSyi7We4eWMloHg0wLIy+ByO1VL3lWbfvcYbb0yxDNlP8Hzyf+OmM5lDKw3yluFQD6/JgH1BiPbWgaST8/db1K8r4PzrzBJqU69alEEb2DVNJwp5kHNuURmGmfiuZ6830wpU3qkdFiQ7OfcKxOAPTJlEUguRy02xrK48Jv8Tjqe4FLLds99i5y5jZu+vcj4lgTIPBrtWyW3TuC3WcDSpwn1B1xlYeUNLUPU10fEk2iJVI8B2plqSiaRTgv43Yfv9KtbA4EURcLFc0fQgNx9/YWKPWzkWNpHpMiim1r9y0WFOccmo7XNnUmdJ5lZmaxLYtalN2pPbS+qRUinRKLw13Trx6M1geQLzaC7HYuYr1xFXYwhEIRPENFrC3U6irGOUXDN8nO3sAk7YA/1f+rRcKOALwMlBbem8w2IQxLjrOOxJE52jZr0CzdV0z71y0V8kDPvqfqWXVgvZZUapOWXwCt/haPIjbxi0YLjj3vA4WCB3n1QkXJ74cD+xpRZRx0WDq9OfONcba7/pOA5JBJiPb9k9EtNyj8XtTZwycEjyeN4GzRbdiy9NyIxIm2U2X5ivxa9p8pURZquq8WN11AUtuOlioZY3GIPgIB/90EQMvF+k4PqU0/meklnwg=
  app: projetpizza
  on:
    repo: Tilanchicha/ProjetPizza
